# HTTP listener configuration
http:
  host:       "0.0.0.0"
  port:       "8081"

# HTTP request properties for NPL Cloud connection
nlp:
  protocol:   "https"
  host:       "api.nlpcloud.io"
  port:       "443"
  apiVersion: "v1"
  model:      "nllb-200-3-3b"
  resource:   "translation"
  url:        "${nlp.protocol}://${nlp.host}:${nlp.port}/${nlp.apiVersion}/${nlp.model}/${nlp.resource}"

# HTTP request properties for Google Translate connection
google:
  protocol:   "https"
  host:       "translate.googleapis.com"
  port:       "443"
  resource:   "translate_a/single"
  url:        "${google.protocol}://${google.host}:${google.port}/${google.resource}"


# HTTP request properties for TranslateDotCom
translate:
  protocol:   "https"
  host:       "translation-api.translate.com"
  port:       "443"
  resource:   "translate"
  apiVersion: "v1"
  url:        "${translate.protocol}://${translate.host}:${translate.port}/${translate.resource}/${translate.apiVersion}/mt"

# HTTP request properties for ChatGPT connection
chatGPT:
  protocol:   "https"
  host:       "api.openai.com"
  port:       "443"
  apiVersion: "v1"
  resource:   "chat/completions"
  url:        "${chatGPT.protocol}://${chatGPT.host}:${chatGPT.port}/${chatGPT.apiVersion}/${chatGPT.resource}"