# APIKey for NLP Cloud API connection
nlp:
  apiKey: "![tP1calrCPi0FDHdajPW0JRS9ANxf4t+Vz+EaNmUrKiZ7UZJoYuH5Iz0sH4cKO2TM]"

# APIKey for ChatGPT connection
chatGPT:
  apiKey: "![6+QCXRPix6EF2bG32KlqGhxIabIQ0+db3A9UuQRj1lt6lhIKYNUxp3XnYVeT1pNbtKRa0SK9vnA=]"

# APIKey for TranslateDotCom API connection
translate:
  apiKey: "![/LeKiGeTu861wfIGm9LqKw==]"

# APIKey for Lecto API connection
lecto:
  apiKey: "![kdWCGZ4QC9G6tL64BBFLk0L94IAirHAA1RPwWDsseq8=]"
