# APIKey for NLP Cloud API connection
nlp:
  apiKey: "![ITCpRzKhGQnE1L/69Sx+KOTCGCtcKqMOmJ4LM0yy59Alqb283P0KVjY0ZrHXyo04]"

# APIKey for ChatGPT connection
chatGPT:
  apiKey: "![6+QCXRPix6EF2bG32KlqGhxIabIQ0+db3A9UuQRj1lt6lhIKYNUxp3XnYVeT1pNbtKRa0SK9vnA=]"

# APIKey for TranslateDotCom API connection
translate:
  apiKey: "![/LeKiGeTu861wfIGm9LqKw==]"

# APIKey for Lecto API connection
lecto:
  apiKey: "![LDrLCThbBr28Lnr+JuL1boTiSFbut6rMApy/dKOYtMY=]"
